# Generated by Django 5.1.3 on 2024-11-08 13:19

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '400x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(upload_to='cats/'),
        ),
    ]
