# Generated by Django 5.1.3 on 2024-11-08 13:20

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catList', '0002_cat_cropping_alter_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '300x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
