# Generated by Django 5.1.3 on 2025-01-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catList', '0005_cat_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='personality_traits',
            field=models.TextField(blank=True),
        ),
    ]
