# Generated by Django 5.1.3 on 2025-01-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catList', '0006_cat_personality_traits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='personality_traits',
            field=models.CharField(max_length=100),
        ),
    ]
