# Generated by Django 5.1.3 on 2025-02-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catList', '0007_alter_cat_personality_traits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='personality_traits',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='sexo',
        ),
        migrations.AddField(
            model_name='cat',
            name='breed_en',
            field=models.CharField(default='joe', max_length=100, verbose_name='Breed (EN)'),
        ),
        migrations.AddField(
            model_name='cat',
            name='breed_es',
            field=models.CharField(default='joe', max_length=100, verbose_name='Raza (ES)'),
        ),
        migrations.AddField(
            model_name='cat',
            name='description_en',
            field=models.TextField(default='joe', verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='cat',
            name='description_es',
            field=models.TextField(default='joe', verbose_name='Descripción (ES)'),
        ),
        migrations.AddField(
            model_name='cat',
            name='name_en',
            field=models.CharField(blank=True, default='joe', max_length=100, null=True, verbose_name='Name (EN)'),
        ),
        migrations.AddField(
            model_name='cat',
            name='name_es',
            field=models.CharField(default='joe', max_length=100, verbose_name='Nombre (ES)'),
        ),
        migrations.AddField(
            model_name='cat',
            name='personality_traits_en',
            field=models.CharField(default='joe', max_length=100, verbose_name='Personality Traits (EN)'),
        ),
        migrations.AddField(
            model_name='cat',
            name='personality_traits_es',
            field=models.CharField(default='joe', max_length=100, verbose_name='Rasgos de personalidad (ES)'),
        ),
        migrations.AddField(
            model_name='cat',
            name='sexo_en',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6, verbose_name='Gender (EN)'),
        ),
        migrations.AddField(
            model_name='cat',
            name='sexo_es',
            field=models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], default='macho', max_length=6, verbose_name='Sexo (ES)'),
        ),
    ]
