# Generated by Django 5.1.3 on 2025-02-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catList', '0008_remove_cat_breed_remove_cat_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
